// gen_voice_samples — host-side build helper that pre-renders each voice
// once and emits a generated C++ header with the resulting PSX ADPCM data.
//
// Why this approach for M2:
//   The PS1 build links with `-nostdlib -fno-builtin`, so cmath functions
//   (sin/exp/pow/tan used by the DSP voice setParams() helpers) are not
//   available. Rendering on the PS1 itself would require either a software
//   libm or rewriting setParams in pure integer math — both larger
//   distractions than the M2 goal of "prove SPU plays our voices".
//
//   Instead we render on the host (same bit-exact DSP code as the eventual
//   PS1 build), encode to PSX ADPCM, and embed the bytes in the binary.
//   The PS1 main loop just DMAs them to SPU RAM and triggers playADPCM.
//
// Usage:
//   ./gen_voice_samples > ../src/generated/voice_samples.h
//
// Re-run whenever any src/dsp/*.cpp coefficient changes.

#include "adpcm_psx.hpp"
#include "dsp/bd_tbridge.hpp"
#include "dsp/hh_six_squares.hpp"
#include "dsp/tb303_stage1.hpp"

#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>

namespace {

constexpr int SR = 22050;

std::vector<int16_t> render_bd(int durationSamples) {
    acid::dsp::BDTBridge bd(SR);
    bd.setParams(0.5f, 0.6f, 0.5f);
    bd.trigger(1.0f);
    std::vector<int16_t> s;
    s.reserve(durationSamples);
    for (int i = 0; i < durationSamples; ++i) s.push_back(bd.tick());
    return s;
}

std::vector<int16_t> render_hh(int durationSamples) {
    acid::dsp::HHSixSquares hh(SR);
    hh.setParams(0.0f, 0.5f, 0.5f);  // closed
    hh.trigger(1.0f);
    std::vector<int16_t> s;
    s.reserve(durationSamples);
    for (int i = 0; i < durationSamples; ++i) s.push_back(hh.tick());
    return s;
}

// One TB-303 saw note at A1 — short, gated for the decay window. We render
// a single note so the demo can re-trigger it via playADPCM (different from
// the host pattern test which sequences 8 notes).
std::vector<int16_t> render_tb303(int durationSamples) {
    acid::dsp::TB303Stage1 v(SR);
    v.setParams(acid::dsp::TB303Wave::Saw, 0.4f, 0.7f, 0.6f, 0.4f, 0.5f);
    v.noteOn(55.0f, false, true);
    std::vector<int16_t> s;
    s.reserve(durationSamples);
    for (int i = 0; i < durationSamples; ++i) {
        if (i == SR / 4) v.noteOff();  // release after 250 ms
        s.push_back(v.tick());
    }
    return s;
}

void emit_array(const std::string &name, const std::vector<uint8_t> &data) {
    std::printf("alignas(4) inline constexpr uint8_t %s[%zu] = {\n",
                name.c_str(), data.size());
    for (size_t i = 0; i < data.size(); ++i) {
        if ((i % 16) == 0) std::printf("    ");
        std::printf("0x%02x", data[i]);
        if (i + 1 != data.size()) std::printf(",");
        if ((i % 16) == 15) std::printf("\n");
        else std::printf(" ");
    }
    if (data.size() % 16) std::printf("\n");
    std::printf("};\n");
    std::printf("inline constexpr unsigned %s_bytes = %zu;\n\n",
                name.c_str(), data.size());
}

}  // namespace

int main() {
    // 1.5 s of BD, 0.5 s of HH (closed = short), 1.0 s of TB303.
    auto bdSamples    = render_bd(SR * 3 / 2);
    auto hhSamples    = render_hh(SR / 2);
    auto tb303Samples = render_tb303(SR);

    auto bdAdpcm    = acid::host::adpcm::encode_one_shot(bdSamples);
    auto hhAdpcm    = acid::host::adpcm::encode_one_shot(hhSamples);
    auto tb303Adpcm = acid::host::adpcm::encode_one_shot(tb303Samples);

    std::printf("// Auto-generated by host_tests/gen_voice_samples.cpp.\n");
    std::printf("// Do NOT edit by hand — re-run the generator instead.\n");
    std::printf("//\n");
    std::printf("// Source rate: %d Hz. Play with SPU sampleRate = 0x0800 (= 0.5×).\n", SR);
    std::printf("\n#pragma once\n#include <cstdint>\n\n");
    std::printf("namespace acid::voice_samples {\n\n");
    emit_array("bd_adpcm",    bdAdpcm);
    emit_array("hh_adpcm",    hhAdpcm);
    emit_array("tb303_adpcm", tb303Adpcm);
    std::printf("}  // namespace acid::voice_samples\n");

    std::fprintf(stderr, "ok: bd=%zu hh=%zu tb303=%zu bytes (ADPCM)\n",
                 bdAdpcm.size(), hhAdpcm.size(), tb303Adpcm.size());
    return 0;
}
